"""Initial migration

Revision ID: e0da8cd9ea2b
Revises: 
Create Date: 2022-04-13 16:39:13.806442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0da8cd9ea2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('sales_channel_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('campaign_prefix', sa.String(length=100), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account', 'platform', 'sales_channel_id', 'country_code', name='uix_account')
    )
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match')
    )
    op.create_table('asin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=10), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.String(length=100), nullable=True),
    sa.Column('target_acos', sa.Float(), nullable=False),
    sa.Column('is_advertising', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin', 'sku', 'account_id', name='uix_asin')
    )
    op.create_index(op.f('ix_asin_asin'), 'asin', ['asin'], unique=False)
    op.create_index(op.f('ix_asin_sku'), 'asin', ['sku'], unique=False)
    op.create_table('bid_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('min_impressions', sa.Integer(), nullable=True),
    sa.Column('lower_acos_target_boundary', sa.Float(), nullable=False),
    sa.Column('upper_acos_target_boundary', sa.Float(), nullable=False),
    sa.Column('max_acos', sa.Float(), nullable=False),
    sa.Column('min_clicks', sa.Integer(), nullable=True),
    sa.Column('bid_increment', sa.Float(), nullable=False),
    sa.Column('bid_decrement', sa.Float(), nullable=False),
    sa.Column('min_bid', sa.Float(), nullable=False),
    sa.Column('max_bid', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['asin_id'], ['asin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin_id', 'match_id', name='uix_bid_target')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid_target')
    op.drop_index(op.f('ix_asin_sku'), table_name='asin')
    op.drop_index(op.f('ix_asin_asin'), table_name='asin')
    op.drop_table('asin')
    op.drop_table('match')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
