"""added different bidding componenets to model

Revision ID: 3cbac0a15391
Revises: 7ecf22a7e106
Create Date: 2022-03-17 09:37:03.784356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cbac0a15391'
down_revision = '7ecf22a7e106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid_asin', sa.Column('compliment_bid_profile_id', sa.Integer(), nullable=True))
    op.add_column('bid_asin', sa.Column('close_bid_profile_id', sa.Integer(), nullable=True))
    op.add_column('bid_asin', sa.Column('loose_bid_profile_id', sa.Integer(), nullable=True))
    op.add_column('bid_asin', sa.Column('substitute_bid_profile_id', sa.Integer(), nullable=True))
    op.add_column('bid_asin', sa.Column('broad_bid_profile_id', sa.Integer(), nullable=True))
    op.add_column('bid_asin', sa.Column('exact_bid_profile_id', sa.Integer(), nullable=True))
    op.add_column('bid_asin', sa.Column('phrase_bid_profile_id', sa.Integer(), nullable=True))
    op.drop_constraint('bid_asin_ibfk_1', 'bid_asin', type_='foreignkey')
    op.create_foreign_key(None, 'bid_asin', 'bid_profile', ['loose_bid_profile_id'], ['bid_profile_id'])
    op.create_foreign_key(None, 'bid_asin', 'bid_profile', ['compliment_bid_profile_id'], ['bid_profile_id'])
    op.create_foreign_key(None, 'bid_asin', 'bid_profile', ['exact_bid_profile_id'], ['bid_profile_id'])
    op.create_foreign_key(None, 'bid_asin', 'bid_profile', ['phrase_bid_profile_id'], ['bid_profile_id'])
    op.create_foreign_key(None, 'bid_asin', 'bid_profile', ['broad_bid_profile_id'], ['bid_profile_id'])
    op.create_foreign_key(None, 'bid_asin', 'bid_profile', ['close_bid_profile_id'], ['bid_profile_id'])
    op.create_foreign_key(None, 'bid_asin', 'bid_profile', ['substitute_bid_profile_id'], ['bid_profile_id'])
    op.drop_column('bid_asin', 'bid_profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid_asin', sa.Column('bid_profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bid_asin', type_='foreignkey')
    op.drop_constraint(None, 'bid_asin', type_='foreignkey')
    op.drop_constraint(None, 'bid_asin', type_='foreignkey')
    op.drop_constraint(None, 'bid_asin', type_='foreignkey')
    op.drop_constraint(None, 'bid_asin', type_='foreignkey')
    op.drop_constraint(None, 'bid_asin', type_='foreignkey')
    op.drop_constraint(None, 'bid_asin', type_='foreignkey')
    op.create_foreign_key('bid_asin_ibfk_1', 'bid_asin', 'bid_profile', ['bid_profile_id'], ['bid_profile_id'])
    op.drop_column('bid_asin', 'phrase_bid_profile_id')
    op.drop_column('bid_asin', 'exact_bid_profile_id')
    op.drop_column('bid_asin', 'broad_bid_profile_id')
    op.drop_column('bid_asin', 'substitute_bid_profile_id')
    op.drop_column('bid_asin', 'loose_bid_profile_id')
    op.drop_column('bid_asin', 'close_bid_profile_id')
    op.drop_column('bid_asin', 'compliment_bid_profile_id')
    # ### end Alembic commands ###
