"""empty message

Revision ID: 7ecf22a7e106
Revises: dbdab00ddcc6
Create Date: 2022-03-15 17:43:22.691882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecf22a7e106'
down_revision = 'dbdab00ddcc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
