"""empty message

Revision ID: dbdab00ddcc6
Revises: 5131d7f899fb
Create Date: 2022-03-15 17:41:59.305661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdab00ddcc6'
down_revision = '5131d7f899fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ass', 'bid_asin', ['asin', 'sku', 'sales_channel_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ass', 'bid_asin', type_='unique')
    # ### end Alembic commands ###
